ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_image MEDIUMTEXT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS password_reset_sent_at DATETIME NULL;
ALTER TABLE admins ADD COLUMN IF NOT EXISTS last_login_at DATETIME NULL;
