CREATE TABLE IF NOT EXISTS materi (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,
    category VARCHAR(128) NOT NULL,
    display_order INT NOT NULL DEFAULT 1,
    short_description TEXT NOT NULL,
    full_description LONGTEXT NOT NULL,
    card_image_name VARCHAR(255) NULL,
    card_image_type VARCHAR(128) NULL,
    card_image_size INT NULL,
    difficulty_level VARCHAR(64) NULL,
    estimated_time VARCHAR(64) NULL,
    page_order INT NOT NULL DEFAULT 1,
    status VARCHAR(64) NOT NULL DEFAULT 'draft',
    active TINYINT(1) NOT NULL DEFAULT 1,
    show_on_page TINYINT(1) NOT NULL DEFAULT 1,
    featured TINYINT(1) NOT NULL DEFAULT 0,
    comments TINYINT(1) NOT NULL DEFAULT 1,
    access_type VARCHAR(64) NULL,
    featured_order INT NULL,
    user_level VARCHAR(64) NOT NULL DEFAULT 'semua_pengguna',
    access_requirement TEXT NULL,
    prerequisite TEXT NULL,
    cta_text VARCHAR(191) NULL,
    cta_target_link VARCHAR(500) NULL,
    cta_url_slug VARCHAR(255) NULL,
    publish_schedule DATETIME NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    INDEX materi_status_order_idx (status, active, show_on_page, page_order, display_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS materi_slides (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    materi_id BIGINT UNSIGNED NOT NULL,
    slide_order INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    content_type VARCHAR(64) NOT NULL DEFAULT 'text',
    content LONGTEXT NULL,
    estimated_time VARCHAR(64) NULL,
    status VARCHAR(64) NOT NULL DEFAULT 'draft',
    image_name VARCHAR(255) NULL,
    image_type VARCHAR(128) NULL,
    image_size INT NULL,
    video_url VARCHAR(1000) NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    INDEX materi_slides_materi_order_idx (materi_id, slide_order),
    CONSTRAINT materi_slides_materi_fk FOREIGN KEY (materi_id) REFERENCES materi(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
