CREATE TABLE IF NOT EXISTS transactions (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNSIGNED NULL,
    user_name VARCHAR(191) NULL,
    email VARCHAR(191) NULL,
    item_type VARCHAR(50) NOT NULL DEFAULT 'workshop',
    item_id BIGINT UNSIGNED NULL,
    item_title VARCHAR(255) NOT NULL,
    amount DECIMAL(14,2) NOT NULL DEFAULT 0,
    currency VARCHAR(10) NOT NULL DEFAULT 'IDR',
    payment_method VARCHAR(100) NULL,
    payment_channel VARCHAR(100) NULL,
    payment_code VARCHAR(191) NULL,
    recipient_name VARCHAR(191) NULL,
    qris_file_name VARCHAR(255) NULL,
    qris_file_type VARCHAR(120) NULL,
    qris_file_size BIGINT UNSIGNED NULL,
    qris_file_path VARCHAR(255) NULL,
    qris_file_url VARCHAR(255) NULL,
    invoice_number VARCHAR(100) NOT NULL UNIQUE,
    reference_number VARCHAR(100) NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'pending',
    paid_at DATETIME NULL,
    due_at DATETIME NULL,
    notes TEXT NULL,
    proof_file_name VARCHAR(255) NULL,
    proof_file_type VARCHAR(120) NULL,
    proof_file_size BIGINT UNSIGNED NULL,
    proof_file_path VARCHAR(255) NULL,
    proof_file_url VARCHAR(255) NULL,
    proof_uploaded_at DATETIME NULL,
    reviewed_at DATETIME NULL,
    reviewed_by VARCHAR(191) NULL,
    rejection_reason TEXT NULL,
    payload_json JSON NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    INDEX idx_transactions_user_id (user_id),
    INDEX idx_transactions_email (email),
    INDEX idx_transactions_status (status),
    INDEX idx_transactions_created_at (created_at)
);

CREATE TABLE IF NOT EXISTS user_entitlements (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    transaction_id BIGINT UNSIGNED NOT NULL,
    user_id BIGINT UNSIGNED NULL,
    email VARCHAR(191) NULL,
    product_type VARCHAR(50) NOT NULL,
    product_id BIGINT UNSIGNED NULL,
    product_title VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'active',
    granted_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    UNIQUE KEY idx_user_entitlements_transaction (transaction_id),
    INDEX idx_user_entitlements_user_id (user_id),
    INDEX idx_user_entitlements_email (email)
);

CREATE TABLE IF NOT EXISTS payment_methods (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(191) NOT NULL,
    method_type VARCHAR(100) NOT NULL DEFAULT 'Transfer Bank',
    channel VARCHAR(100) NULL,
    recipient_name VARCHAR(191) NULL,
    payment_code VARCHAR(191) NULL,
    qris_file_name VARCHAR(255) NULL,
    qris_file_type VARCHAR(120) NULL,
    qris_file_size BIGINT UNSIGNED NULL,
    qris_file_path VARCHAR(255) NULL,
    qris_file_url VARCHAR(255) NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    INDEX idx_payment_methods_active (is_active)
);
