<?php
declare(strict_types=1);

require dirname(__DIR__) . '/api/support/autoload-app.php';
use Arduflow\Api\Services\PayoutService;

$pdo = new PDO('sqlite::memory:', null, null, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION, PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC]);
$pdo->exec('CREATE TABLE users(id INTEGER PRIMARY KEY, name TEXT, email TEXT);
    INSERT INTO users VALUES(1,"Test Owner","owner@example.com");
    CREATE TABLE project_submissions(id INTEGER PRIMARY KEY,title TEXT,payload_json TEXT,deleted_at TEXT);
    INSERT INTO project_submissions VALUES(70,"Fixture project",\'{"userId":1}\',NULL),(71,"Other owner",\'{"userId":2}\',NULL)');
$pdo->exec(file_get_contents(dirname(__DIR__) . '/migrations/sqlite/008_transactions.sql'));
$pdo->exec('ALTER TABLE transactions ADD COLUMN deleted_at TEXT');
$pdo->exec("INSERT INTO transactions(user_id,item_type,item_id,item_title,amount,currency,invoice_number,status,created_at,updated_at) VALUES(1,'project',70,'Fixture project',100000,'IDR','sale-1','paid','2026-01-01','2026-01-01')");
$user = ['id' => 1, 'name' => 'Test Owner', 'email' => 'owner@example.com', 'email_verified_at' => '2026-01-01', 'password_hash' => password_hash('AccountPassword9!', PASSWORD_DEFAULT)];
$clock = 1800000000;
$mail = [];
$sender = static function (array $user, string $code, string $description) use (&$mail): bool { $mail[] = [$code, $description]; return true; };
$service = new PayoutService($pdo, $sender, $clock);
$service->install();
$checks = 0;
$check = static function (bool $condition, string $label) use (&$checks): void { if (!$condition) throw new RuntimeException($label); $checks++; };
$denied = static function (callable $callback, int $status, string $label) use ($check): void {
    try { $callback(); } catch (RuntimeException $error) { $check($error->getCode() === $status, $label . ': ' . $error->getMessage()); return; }
    throw new RuntimeException('Expected denial: ' . $label);
};
$tick = static function (int $seconds) use (&$service, &$clock, $pdo, $sender): void { $clock += $seconds; $service = new PayoutService($pdo, $sender, $clock); };
$latestCode = static function () use (&$mail): string { return $mail[array_key_last($mail)][0]; };
$check($service->balances(1)[0]['available'] === 90000, 'commission calculated on server');
$denied(fn() => $service->request($user, 'pin', ['password' => 'AccountPassword9!', 'newPin' => '123456']), 422, 'weak PIN denied');
$denied(fn() => $service->request($user, 'pin', ['password' => 'bad', 'newPin' => '827495']), 422, 'wrong account password denied');
$setup = $service->request($user, 'pin', ['password' => 'AccountPassword9!', 'newPin' => '827495']);
$check(!isset($setup['code']) && !isset($setup['summary']['hash']), 'response has no credentials');
$service->confirm($user, ['challengeId' => $setup['challengeId'], 'code' => $latestCode()]);
$check($service->status($user)['hasPin'], 'activation succeeds');
$tick(61);
$account = $service->request($user, 'account', ['password' => 'AccountPassword9!', 'pin' => '827495', 'bank' => 'BCA', 'number' => '1234567890', 'name' => 'Test Owner']);
$service->confirm($user, ['challengeId' => $account['challengeId'], 'code' => $latestCode()]);
$accountId = (int) $service->status($user)['accounts'][0]['id'];
$check($service->status($user)['accounts'][0]['number'] === '•••• 7890', 'account number masked');
$denied(fn() => $service->request($user, 'payout', ['accountId' => $accountId, 'projectIds' => [70]]), 409, 'new account cooling period');
$tick(86401);
$denied(fn() => $service->request($user, 'payout', ['accountId' => $accountId, 'projectIds' => [71]]), 422, 'other owners cannot withdraw');
$denied(fn() => $service->request($user, 'payout', ['accountId' => $accountId, 'projectIds' => [70], 'amount' => 90001]), 422, 'insufficient balance denied');
$quote = $service->request($user, 'payout', ['accountId' => $accountId, 'projectIds' => [70], 'amount' => 40000]);
$otp = $latestCode();
$check(str_contains($mail[array_key_last($mail)][1], '40.000') && str_contains($mail[array_key_last($mail)][1], '7890'), 'OTP email binds amount and destination');
for ($i = 1; $i <= 5; $i++) $denied(fn() => $service->confirm($user, ['challengeId' => $quote['challengeId'], 'code' => $otp, 'pin' => '000000']), $i === 5 ? 429 : 422, 'PIN rate limit');
$denied(fn() => $service->confirm($user, ['challengeId' => $quote['challengeId'], 'code' => $otp, 'pin' => '827495']), 429, 'correct PIN cannot bypass active lock');
$check($service->balances(1)[0]['available'] === 90000, 'failed PIN never reserves money');
$tick(901);
$denied(fn() => $service->confirm($user, ['challengeId' => $quote['challengeId'], 'code' => $otp, 'pin' => '827495']), 409, 'expired OTP denied');
$quote = $service->request($user, 'payout', ['accountId' => $accountId, 'projectIds' => [70], 'amount' => 40000]);
$otp = $latestCode();
$pdo->exec('BEGIN IMMEDIATE');
$result = $service->confirm($user, ['challengeId' => $quote['challengeId'], 'code' => $otp, 'pin' => '827495', 'amount' => 999999, 'accountId' => 999]);
$pdo->exec('COMMIT');
$check(count($result['transactionIds']) === 1, 'one payout created');
$check($service->balances(1)[0]['available'] === 50000, 'pending payout reserves balance');
$row = $pdo->query('SELECT * FROM transactions WHERE item_type="project_payout"')->fetch();
$check((int) $row['amount'] === 40000 && $row['payment_code'] === '1234567890', 'tampered confirmation ignored; server snapshot used');
$check(!str_contains($row['payload_json'], '827495') && !str_contains($row['payload_json'], $otp), 'no PIN or OTP persisted in transaction');
$again = $service->confirm($user, ['challengeId' => $quote['challengeId'], 'code' => $otp, 'pin' => '827495']);
$check($again['transactionIds'] === $result['transactionIds'] && $again['replayed'] && $service->balances(1)[0]['available'] === 50000, 'retry returns original transaction');
$tick(61);
$stale = $service->request($user, 'payout', ['accountId' => $accountId, 'projectIds' => [70], 'amount' => 50000]);
$staleCode = $latestCode();
$pdo->exec('UPDATE transactions SET amount=45000 WHERE item_type="project_payout"');
$denied(fn() => $service->confirm($user, ['challengeId' => $stale['challengeId'], 'code' => $staleCode, 'pin' => '827495']), 409, 'balance rechecked on confirmation');
$pdo->exec('UPDATE transactions SET status="rejected" WHERE item_type="project_payout"');
$check($service->balances(1)[0]['available'] === 90000, 'rejection releases reservation');
$tick(61);
$reset = $service->request($user, 'pin', ['password' => 'AccountPassword9!', 'newPin' => '926481']);
$service->confirm($user, ['challengeId' => $reset['challengeId'], 'code' => $latestCode()]);
$check($service->status($user)['cooldownUntil'] === $clock + 86400, 'reset enforces 24-hour hold');
$denied(fn() => $service->confirm($user, ['challengeId' => $stale['challengeId'], 'code' => $staleCode, 'pin' => '926481']), 409, 'reset invalidates outstanding authorizations');
$denied(fn() => $service->request($user, 'payout', ['accountId' => $accountId, 'projectIds' => [70]]), 409, 'reset cooldown enforced server-side');
$tick(86401);
$offline = new PayoutService($pdo, static fn(): bool => false, $clock);
$denied(fn() => $offline->request($user, 'payout', ['accountId' => $accountId, 'projectIds' => [70]]), 503, 'mail failure fails closed');
$check($service->balances(1)[0]['available'] === 90000, 'mail failure leaves balance unchanged');
echo "PASS: {$checks} payout security assertions\n";
